version: '3.8'

services:
  corebridge-health-monitor:
    build: .
    container_name: corebridge-health-monitor
    ports:
      - "3002:3002"
    networks:
      - corebridge-network
    environment:
      - NODE_ENV=production
      - PORT=3002
      - CORE_API_URL=http://corebridge-core:4001
      - RABBITMQ_HOST=corebridge-rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=admin
      - RABBITMQ_PASS=password
      - REDIS_HOST=corebridge-redis
      - REDIS_PORT=6379
      - DB_HOST=corebridge-postgres
      - DB_PORT=5432
      - DB_NAME=corebridge
      - DB_USER=corebridge
      - DB_PASSWORD=corebridge123
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  corebridge-network:
    external: true
    name: corebridge-core_app-network 